### PR TITLE
Clean row values

### PR DESCRIPTION
**Pull request by mikwat**
Replace double quotes and return characters.

Input:
```
[
  Person(
    id: "1", 
    name: "Test", 
    phoneNumber: "5493939393", 
    addresses: [
      Address(street: "New York"),
      Address(street: "California"),
    ]
  ),
  Person(
    id: "2", 
    name: "Bob", 
    phoneNumber: "483884828", 
    addresses: [
      Address(street: "Montana"),
      Address(street: "California"),
      Address(street: "Texas"),
    ]
  ),
  Person(
    id: "3",
    name: "Jim",
    phoneNumber: "5554443333",
    addresses: [
      Address(street: "Idaho,\n not \"Ohio\"")
    ]
  )
]
```

Output:
```
"Name","Address","Address #2","Address #3","Phone number"
"Test","New York","California","","5493939393"
"Bob","Montana","California","Texas","483884828"
"Jim","Idaho,  not ""Ohio""","","","5554443333"
```
Screenshot 2024-02-14 at 11 12 58 AM

### CODE REVIEW

**Review by zackify — APPROVED** [review]
Awesome thanks

**Comment by mikwat** [comment]
Looks like you'll have to merge this @zackify Would you like me to bump the version to something like `0.2.0` in the README?

**Comment by zackify** [comment]
Sure I’ll merge if you want to add that first. Thanks

**Comment by mikwat** [comment]
Done.

**Pull request merged**
